extensionprops: {}
openapi: 3.0.0
components:
  extensionprops: {}
  schemas:
    CAType:
      ref: ""
      value:
        extensionprops: {}
        type: string
        enum:
        - pki
        - dmsenroller
    CertificateContent:
      ref: ""
      value:
        extensionprops: {}
        type: object
        properties:
          pem_base64:
            ref: ""
            value:
              extensionprops: {}
              type: string
          public_key_base64:
            ref: ""
            value:
              extensionprops: {}
              type: string
    CertificateStatus:
      ref: ""
      value:
        extensionprops: {}
        type: string
        enum:
        - issued
        - expired
    CertificateSubject:
      ref: ""
      value:
        extensionprops: {}
        type: object
        properties:
          common_name:
            ref: ""
            value:
              extensionprops: {}
              type: string
          country:
            ref: ""
            value:
              extensionprops: {}
              type: string
          locality:
            ref: ""
            value:
              extensionprops: {}
              type: string
          organization:
            ref: ""
            value:
              extensionprops: {}
              type: string
          organization_unit:
            ref: ""
            value:
              extensionprops: {}
              type: string
          state:
            ref: ""
            value:
              extensionprops: {}
              type: string
    KeyMetadata:
      ref: ""
      value:
        extensionprops: {}
        type: object
        properties:
          bits:
            ref: ""
            value:
              extensionprops: {}
              type: integer
          strength:
            ref: ""
            value:
              extensionprops: {}
              type: string
          type:
            ref: ""
            value:
              extensionprops: {}
              type: string
    LamassuCA:
      ref: ""
      value:
        extensionprops: {}
        type: object
        properties:
          ca_ttl:
            ref: ""
            value:
              extensionprops: {}
              type: integer
          certificate:
            ref: '#/components/schemas/CertificateContent'
            value: null
          enroller_ttl:
            ref: ""
            value:
              extensionprops: {}
              type: integer
          key_metadata:
            ref: '#/components/schemas/KeyMetadata'
            value: null
          name:
            ref: ""
            value:
              extensionprops: {}
              type: string
          serial_number:
            ref: ""
            value:
              extensionprops: {}
              type: string
          status:
            ref: '#/components/schemas/CertificateStatus'
            value: null
          subject:
            ref: '#/components/schemas/CertificateSubject'
            value: null
          valid_from:
            ref: ""
            value:
              extensionprops: {}
              type: string
          valid_to:
            ref: ""
            value:
              extensionprops: {}
              type: string
  requestBodies:
    CreateCARequest:
      ref: ""
      value:
        extensionprops: {}
        description: Request used for creating a new Certificate Authority
        required: true
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  ca_ttl:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: integer
                  enroller_ttl:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: integer
                  key_metadata:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: object
                      properties:
                        bits:
                          ref: ""
                          value:
                            extensionprops: {}
                            type: integer
                        type:
                          ref: ""
                          value:
                            extensionprops: {}
                            type: string
                  subject:
                    ref: '#/components/schemas/CertificateSubject'
                    value: null
    ImportCARequest:
      ref: ""
      value:
        extensionprops: {}
        description: Request used for importing a Certificate Authority
        required: true
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  ca_ttl:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: integer
                  enroller_ttl:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: integer
                  key_metadata:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: object
                      properties:
                        bits:
                          ref: ""
                          value:
                            extensionprops: {}
                            type: integer
                        type:
                          ref: ""
                          value:
                            extensionprops: {}
                            type: string
                  subject:
                    ref: '#/components/schemas/CertificateSubject'
                    value: null
    SignCertificateRequest:
      ref: ""
      value:
        extensionprops: {}
        description: Request used for getting all a certificates
        required: true
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  csr:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: string
    postCSRRequest:
      ref: ""
      value:
        extensionprops: {}
        description: Request used for getting all a certificates
        required: true
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  csr:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: string
  responses:
    CreateCAResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after creating a CA.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: '#/components/schemas/LamassuCA'
              value: null
    DeleteCertResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after importing a CA.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
    ErrorResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response when errors happen.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  error:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: string
    GetCAResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after getting a CA.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                type: array
                items:
                  ref: '#/components/schemas/LamassuCA'
                  value: null
    GetCertResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after getting a certificate.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: '#/components/schemas/LamassuCA'
              value: null
    GetIssuedCertsResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after getting list of issued certificates.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                type: array
                items:
                  ref: '#/components/schemas/LamassuCA'
                  value: null
    HealthResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after healthchecking.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  healthy:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: boolean
    ImportCAResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after importing a CA.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
    RevokeCAResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after revoking a CA.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
    SignCertificateResponse:
      ref: ""
      value:
        extensionprops: {}
        description: Response returned back after signing certificate.
        content:
          application/json:
            extensionprops: {}
            schema:
              ref: ""
              value:
                extensionprops: {}
                properties:
                  crt:
                    ref: ""
                    value:
                      extensionprops: {}
                      type: boolean
info:
  extensionprops: {}
  title: Lamassu CA API
  description: REST API used for interacting with Lamassu CA
  contact:
    extensionprops: {}
    url: https://github.com/lamassuiot
  license:
    extensionprops: {}
    name: MPL v2.0
    url: https://github.com/lamassuiot/lamassu-compose/blob/main/LICENSE
  version: 0.0.0
paths:
  /v1/{caType}:
    extensionprops: {}
    get:
      extensionprops: {}
      description: Get all CAs
      operationId: GetCAs
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caType
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              enum:
              - pki
              - dmsenroller
      responses:
        "200":
          ref: '#/components/responses/GetCAResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
  /v1/{caType}/{caName}/cert/{serialNumber}:
    extensionprops: {}
    delete:
      extensionprops: {}
      description: Revoke certificate issued by {caName} and {serialNumber}
      operationId: DeleteCert
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      - ref: ""
        value:
          extensionprops: {}
          name: caType
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              enum:
              - pki
              - dmsenroller
      - ref: ""
        value:
          extensionprops: {}
          name: serialNumber
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      responses:
        "200":
          ref: '#/components/responses/DeleteCertResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
    get:
      extensionprops: {}
      description: Get certificate by {caName} and {serialNumber}
      operationId: GetCert
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      - ref: ""
        value:
          extensionprops: {}
          name: caType
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              enum:
              - pki
              - dmsenroller
      - ref: ""
        value:
          extensionprops: {}
          name: serialNumber
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      responses:
        "200":
          ref: '#/components/responses/GetCertResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
  /v1/{caType}/{caName}/issued:
    extensionprops: {}
    get:
      extensionprops: {}
      description: Get Issued certificates by {caName}
      operationId: GetIssuedCerts
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      - ref: ""
        value:
          extensionprops: {}
          name: caType
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              enum:
              - pki
              - dmsenroller
      responses:
        "200":
          ref: '#/components/responses/GetIssuedCertsResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
  /v1/{caType}/{caName}/sign:
    extensionprops: {}
    post:
      extensionprops: {}
      description: Sign CSR by {caName}
      operationId: SignCertificate
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      - ref: ""
        value:
          extensionprops: {}
          name: caType
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              enum:
              - pki
              - dmsenroller
      requestBody:
        ref: '#/components/requestBodies/SignCertificateRequest'
        value: null
      responses:
        "200":
          ref: '#/components/responses/SignCertificateResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
  /v1/health:
    extensionprops: {}
    get:
      extensionprops: {}
      description: Get health status
      operationId: Health
      responses:
        "200":
          ref: '#/components/responses/HealthResponse'
          value: null
  /v1/pki/{caName}:
    extensionprops: {}
    delete:
      extensionprops: {}
      description: Revoke CA
      operationId: RevokeCA
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      responses:
        "200":
          ref: '#/components/responses/RevokeCAResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
    post:
      extensionprops: {}
      description: Create new CA using Form
      operationId: CreateCA
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      requestBody:
        ref: '#/components/requestBodies/CreateCARequest'
        value: null
      responses:
        "200":
          ref: '#/components/responses/CreateCAResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
  /v1/pki/import/{caName}:
    extensionprops: {}
    post:
      extensionprops: {}
      description: Import existing crt and key
      operationId: ImportCA
      parameters:
      - ref: ""
        value:
          extensionprops: {}
          name: caName
          in: path
          required: true
          schema:
            ref: ""
            value:
              extensionprops: {}
              type: string
      requestBody:
        ref: '#/components/requestBodies/postCSRRequest'
        value: null
      responses:
        "200":
          ref: '#/components/responses/ImportCAResponse'
          value: null
        "400":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "401":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "403":
          ref: '#/components/responses/ErrorResponse'
          value: null
        "500":
          ref: '#/components/responses/ErrorResponse'
          value: null
servers:
- extensionprops: {}
  url: /
  description: Current Server
